name: Build and Push Metalmon Image

on:
  push:
    branches:
      - main
    paths:
      - 'images/production/**'
      - '.github/workflows/build_metalmon.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'images/production/**'
      - '.github/workflows/build_metalmon.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --allow-insecure-entitlement network.host

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/production/Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: metalmon/frappe:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_STEP_TIMEOUT=1200
          platforms: linux/amd64
          allow: network.host
          provenance: false
