name: Lint

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/workflows/lint.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint black flake8

      - name: Lint YAML files
        run: yamllint .

      - name: Lint Python files
        run: |
          black . --check
          flake8 .
