name: Security Scan

on:
  push:
    branches:
      - main
    paths:
      - 'images/production/**'
      - '.github/workflows/security.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'images/production/**'
      - '.github/workflows/security.yml'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    needs: []  # Remove if you want to run after build job
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest image
        run: docker pull metalmon/frappe:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'metalmon/frappe:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '10m'
          scanners: 'vuln,secret'
          skip-files: '**/*discovery_cache/**'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
