name: Security Scan

on:
  push:
    branches:
      - main
    paths:
      - 'images/production/**'
      - '.github/workflows/security.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'images/production/**'
      - '.github/workflows/security.yml'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --allow-insecure-entitlement network.host

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/production/Containerfile
          push: false
          tags: metalmon/frappe:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_STEP_TIMEOUT=1200
          platforms: linux/amd64
          allow:
            - network.host
          load: true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'metalmon/frappe:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '10m'
          scanners: 'vuln,secret,config'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'