name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'tests/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --allow-insecure-entitlement network.host

      - name: Build test environment
        uses: docker/build-push-action@v5
        with:
          context: .
          file: tests/Dockerfile
          load: true
          tags: test-image:latest
          allow: network.host

      - name: Run tests
        run: docker run --rm test-image:latest